[package]
name = "tic-tac-toe"
version = "0.1.0"
authors = ["Yacin Tmimi <ytmimi@horizonmedia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
